export interface Patient {
    id: number,
    name: string,
    height: number,
    weight: number,
    birthday: Date,
    religion: string,
    job: string,
    education: string,
    status: string,
    gender: boolean,
    residentNumber: string,
    address: string,
    slug: string,
}