export interface HeadToToeCheckup {
    head: {
        hairDistribution: string,
        scalp: string,
        tenderness: string,
        facialMovementSymmetry: boolean,
        facialSensation: string,
        notes: string,
    },
    eyes: {
        symmetry: boolean,
        eyebrowDistribution: string,
        eyelashDistribution: string,
        conjunctiva: string,
        schlera: string,
        cornea: string,
        perrla: boolean,
        cardinal: string,
        snellenChart: string,
        notes: string,
    }
    ears: {
        auriclePalpation: string,
        tympanicMembrane: string,
        weberTest: string,
        rinneTest: string,
        whisperTest: string,
        notes: string,
    },
    nose: {
        symmetryPalpation: string,
        nostrilInterior: string,
        naresPatency: string,
        smell: string,
        sinusesPalpation: string,
        notes: string,
    },
    mouthThroat: {
        lips: string,
        teethGums: string,
        buccalMucosa: string,
        tongue: string,
        jawJoint: string,
        notes: string,
    },
    neckShoulders: {
        neckRangeOfMotions: string,
        shoulderShrug: string,
        lymphNodes: string,
        neckAndTracheaPalpation: string,
        jvd: string,
        notes: string,
    },
    lungsThorax: {
        lungAuscultation: string,
        respiratoryExclusion: string,
        thoraxPalpation: string,
        spinalCurvature: string,
        notes: string,
    },
    circulatorySystem: {
        carotidArteryPalpation: string,
        heartAuscultation: string,
        notes: string,
    },
    gastrointestinal: {
        abdominalInspection: string,
        bowelSoundAuscultation: string,
        abdomenPalpation: string,
        bowelProblem: boolean,
        notes: string,
    },
    armsHands: {
        romAndStrength: string,
        armPulses: string,
        capRefill: string,
        skinTurgor: string,
        sensation: string,
        notes: string,
    },
    legsFeet: {
        romAndStrength: string,
        legPulses: string,
        capRefill: string,
        sensation: string,
        gaitAssessment: string,
        notes: string,
    },
    genitourinary: {
        pubicHair: string,
        tendernessLumpsLesions: string,
        notes: string,
    },
    breast: {
        breastPalpation: string,
        notes: string,
    }
}